# -*- coding: utf-8 -*-
"""Shaoqian_Chen_HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wAV3tTUL-ljICO_PyxSYvMSdT40pzx0n
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
import numpy as np
import matplotlib.pyplot as plt
import time
import random

np.set_printoptions(suppress=True) # Suppress scientific notation while printing numbers
# %matplotlib inline

import csv
import json

"""# Task 1"""

def task1(inputfile,outputfile):
    import csv
    csv1 = csv.reader(open(inputfile,"rt"))
    sort = list(csv1)
    biglist = [[],[],[],[],[],[],[],[],[],[],[],[]]
    for i in range(1,len(sort)):
      if (sort[i][1]=="108"):
        biglist[11].append(int(sort[i][2]))
      if (sort[i][1]=="107"):
        biglist[10].append(int(sort[i][2]))
      if (sort[i][1]=="106"):
        biglist[9].append(int(sort[i][2]))
      if (sort[i][1]=="105"):
        biglist[8].append(int(sort[i][2]))
      if (sort[i][1]=="104"):
        biglist[7].append(int(sort[i][2]))
      if (sort[i][1]=="103"):
        biglist[6].append(int(sort[i][2]))
      if (sort[i][1]=="102"):
        biglist[5].append(int(sort[i][2]))
      if (sort[i][1]=="101"):
        biglist[4].append(int(sort[i][2]))
      if (sort[i][1]=="100"):
        biglist[3].append(int(sort[i][2]))
      if (sort[i][1]=="99"):
        biglist[2].append(int(sort[i][2]))
      if (sort[i][1]=="98"):
        biglist[1].append(int(sort[i][2]))
      if (sort[i][1]=="97"):
        biglist[0].append(int(sort[i][2]))
    tasklist = []
    for j in biglist:
      if len(j)==0:
        tasklist.append(0)
      else:
        tasklist.append(round(sum(j)/len(j),1))  
    movieID = [97,98,99,100,101,102,103,104,105,106,107,108]
    
    with open(outputfile, 'w', newline='') as file:
        writer = csv.writer(file)
        for i in range(len(tasklist)):
          writer.writerow([movieID[i],tasklist[i]])

task1("gdrive/My Drive/movies.csv","gdrive/My Drive/task1.csv")







"""# Task 2"""

def task2(inputfile,outputfile):
    import csv
    csv1 = csv.reader(open(inputfile,"rt"))
    sort = list(csv1)
    biglist = [[],[],[],[],[],[],[],[],[],[],[],[]]
    for i in range(1,len(sort)):
      if (sort[i][1]=="108"):
        biglist[11].append(int(sort[i][2]))
      if (sort[i][1]=="107"):
        biglist[10].append(int(sort[i][2]))
      if (sort[i][1]=="106"):
        biglist[9].append(int(sort[i][2]))
      if (sort[i][1]=="105"):
        biglist[8].append(int(sort[i][2]))
      if (sort[i][1]=="104"):
        biglist[7].append(int(sort[i][2]))
      if (sort[i][1]=="103"):
        biglist[6].append(int(sort[i][2]))
      if (sort[i][1]=="102"):
        biglist[5].append(int(sort[i][2]))
      if (sort[i][1]=="101"):
        biglist[4].append(int(sort[i][2]))
      if (sort[i][1]=="100"):
        biglist[3].append(int(sort[i][2]))
      if (sort[i][1]=="99"):
        biglist[2].append(int(sort[i][2]))
      if (sort[i][1]=="98"):
        biglist[1].append(int(sort[i][2]))
      if (sort[i][1]=="97"):
        biglist[0].append(int(sort[i][2]))
    tasklist = []
    for j in biglist:
      if len(j)==0:
        tasklist.append(0)
      else:
        tasklist.append(round(sum(j)/len(j),1))  
    movieID = [97,98,99,100,101,102,103,104,105,106,107,108]
    
    with open(outputfile, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["movieID","avg_rating"])
        for i in range(len(tasklist)):
          writer.writerow([movieID[i],tasklist[i]])

task2("gdrive/My Drive/movies.csv","gdrive/My Drive/task2.csv")





"""# Task 3"""

def task3(jsoninput,jsonoutput):
    import csv
    import json
    with open(jsoninput) as f:
        data = json.load(f)
    biglist3 = [[],[],[],[],[],[],[],[],[],[],[],[]]
    for i in range(len(data["data"])):
      if (data["data"][i][1]==108):
        biglist3[11].append(int(data["data"][i][2]))
      if (data["data"][i][1]==107):
        biglist3[10].append(int(data["data"][i][2]))
      if (data["data"][i][1]==106):
        biglist3[9].append(int(data["data"][i][2]))
      if (data["data"][i][1]==105):
        biglist3[8].append(int(data["data"][i][2]))
      if (data["data"][i][1]==104):
        biglist3[7].append(int(data["data"][i][2]))
      if (data["data"][i][1]==103):
        biglist3[6].append(int(data["data"][i][2]))
      if (data["data"][i][1]==102):
        biglist3[5].append(int(data["data"][i][2]))
      if (data["data"][i][1]==101):
        biglist3[4].append(int(data["data"][i][2]))
      if (data["data"][i][1]==100):
        biglist3[3].append(int(data["data"][i][2]))
      if (data["data"][i][1]==99):
        biglist3[2].append(int(data["data"][i][2]))
      if (data["data"][i][1]==98):
        biglist3[1].append(int(data["data"][i][2]))
      if (data["data"][i][1]==97):
        biglist3[0].append(int(data["data"][i][2]))
    tasklist3 = []
    for j in biglist3:
      if len(j)==0:
        tasklist3.append(0)
      else:
        tasklist3.append(round(sum(j)/len(j),1))  
    movieID = [97,98,99,100,101,102,103,104,105,106,107,108]
    a = {"metadata":{"info":{"author": "Shaoqian Chen", "organization": "USC", "creation_date": "02/24/2020"},"columns":{"movieID":"movie id for the movies","avg_rating":"avg rating given to the movies",}},"data":[[k,v]for k, v in zip(movieID, tasklist3)]}
    with open(jsonoutput, 'w') as json_file:
      json.dump(a,json_file,indent=1)

task3("gdrive/My Drive/movies.json","gdrive/My Drive/task3.json")



"""# Task 4"""

def task4(inputjson,outputcsv):
    import csv
    import json
    with open(inputjson) as f:
        data = json.load(f)
        
    with open(outputcsv, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["author","organization","creation_date"])
        writer.writerow([data["metadata"]["info"]["author"],data["metadata"]["info"]["organization"],data["metadata"]["info"]["creation_date"]])
        writer.writerow([])
        writer.writerow(['movieID',"avg_rating"])
        for i in range(len(data["data"])):
          writer.writerow([data["data"][i][0],data["data"][i][1]])

task4("gdrive/My Drive/task3.json","gdrive/My Drive/task4.csv")

#Extra Credit

"""# Extra Credit"""

import csv
with open("gdrive/My Drive/task4.csv","r") as f:
    dt = csv.reader(f,delimiter=',')
    for row in dt:
        print(",".join(row))





"""# Task 5"""

def task5(inputcsv,outputjson):
  ! pip install tableschema
  from tableschema import Table 
  table = Table(inputcsv)
  table.read(keyed=True)

  table.infer()
  table.schema.descriptor

  table.schema.descriptor["missingValues"] = "N/A"
  table.schema.commit()
  table.schema.valid
  table.schema.errors

  table.schema.descriptor["missingValues"] = "N/A"
  table.schema.commit()
  table.schema.valid
  table.schema.errors

  table.read(keyed=True)
  table.schema.save(outputjson)

task5("gdrive/My Drive/movies.csv","gdrive/My Drive/schema.json")

